package mcp

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/fastschema/qjs"

	"github.com/zanellm/zanellm/internal/jsonx"
)

// sandboxPreamble removes dangerous global objects exposed by QuickJS's std
// and os modules, replaces console with a capture buffer, and deletes timer
// APIs before user code executes. Console output is captured into __logs and
// returned in the execution result for debugging.
const sandboxPreamble = "delete globalThis.std;" +
	"delete globalThis.os;" +
	"delete globalThis.bjson;" +
	"delete globalThis.setTimeout;" +
	"delete globalThis.setInterval;" +
	"delete globalThis.clearTimeout;" +
	"delete globalThis.clearInterval;" +
	"delete globalThis.print;" +
	"globalThis.__logs = [];" +
	"globalThis.console = {" +
	"log: (...a) => __logs.push({level:'log',msg:a.map(String).join(' ')})," +
	"warn: (...a) => __logs.push({level:'warn',msg:a.map(String).join(' ')})," +
	"error: (...a) => __logs.push({level:'error',msg:a.map(String).join(' ')})," +
	"info: (...a) => __logs.push({level:'info',msg:a.map(String).join(' ')})," +
	"debug: (...a) => __logs.push({level:'debug',msg:a.map(String).join(' ')})" +
	"};\n"

// ToolCaller executes a single MCP tool call through the ZaneLLM gateway,
// preserving authentication, access control, session management, metrics,
// and usage logging. serverAlias identifies the upstream MCP server, toolName
// is the tool to invoke, and args is the JSON-encoded arguments object.
type ToolCaller func(ctx context.Context, serverAlias, toolName string, args jsonx.RawMessage) (jsonx.RawMessage, error)

// ExecuteParams holds the input for a Code Mode script execution.
type ExecuteParams struct {
	// Code is the JavaScript source code to execute.
	Code string
	// ServerTools maps server alias to the list of tools available from that
	// server. Only these tools are injected into the sandbox.
	ServerTools map[string][]Tool
	// CallTool routes individual tool calls through the ZaneLLM gateway.
	CallTool ToolCaller
	// MaxToolCalls is the maximum number of tool calls allowed per execution.
	// Zero means no limit.
	MaxToolCalls int
	// ExecutionID is a UUIDv7 generated by the caller that uniquely identifies
	// this execute_code invocation. It is threaded through to every tool call
	// log so that all tool calls from one execution can be grouped together.
	ExecutionID string
	// OnToolResult is an optional hook called after each successful tool call
	// with the unwrapped result. It is invoked in a separate goroutine and must
	// not block. serverAlias and toolName identify the tool; result is the
	// unwrapped JSON payload.
	OnToolResult func(serverAlias, toolName string, result jsonx.RawMessage)
}

// ExecuteResult holds the output of a Code Mode script execution.
type ExecuteResult struct {
	// ExecutionID is the UUIDv7 that was passed in via ExecuteParams. It
	// groups all tool call log entries for this execution.
	ExecutionID string `json:"execution_id"`
	// Result is the final return value of the script, JSON-encoded.
	Result jsonx.RawMessage `json:"result"`
	// ToolCalls records every tool invocation made during execution.
	ToolCalls []ToolCallLog `json:"tool_calls"`
	// Logs captures console.log/warn/error/info/debug output from the script.
	// Each entry has "level" and "msg" fields.
	Logs []ConsoleLog `json:"logs"`
	// DurationMS is the total wall-clock execution time in milliseconds.
	DurationMS int64 `json:"duration_ms"`
	// Error is non-empty when the script failed (syntax error, timeout, OOM,
	// or unhandled exception).
	Error string `json:"error,omitempty"`
}

// ConsoleLog is a single console output captured from a Code Mode script.
type ConsoleLog struct {
	// Level is the console method that was called (log, warn, error, info, debug).
	Level string `json:"level"`
	// Msg is the concatenated string representation of all arguments.
	Msg string `json:"msg"`
}

// ToolCallLog records a single tool invocation made from within a Code Mode script.
type ToolCallLog struct {
	// Server is the MCP server alias.
	Server string `json:"server"`
	// Tool is the tool name as registered on the upstream server.
	Tool string `json:"tool"`
	// DurationMS is the tool call round-trip time in milliseconds.
	DurationMS int64 `json:"duration_ms"`
	// Status is "success" or "error".
	Status string `json:"status"`
}

// Executor runs Code Mode scripts in sandboxed QJS runtimes.
type Executor struct {
	pool *RuntimePool
}

// NewExecutor creates a Code Mode executor backed by the given runtime pool.
func NewExecutor(pool *RuntimePool) *Executor {
	return &Executor{pool: pool}
}

// Execute runs JavaScript code in a sandboxed QJS runtime with MCP tools
// injected as async functions. Returns the execution result including all
// tool call logs. The runtime is acquired from the pool and always discarded
// after execution to prevent cross-user JS global state leakage.
func (e *Executor) Execute(ctx context.Context, params ExecuteParams) (res *ExecuteResult, retErr error) {
	rt, err := e.pool.Acquire(ctx)
	if err != nil {
		return nil, fmt.Errorf("acquire runtime: %w", err)
	}

	// Always release with healthy=false. Runtimes are never reused across
	// executions — this prevents cross-user JS global state leakage.
	defer func() {
		e.pool.Release(rt, false)
	}()

	start := time.Now()

	result := &ExecuteResult{
		ExecutionID: params.ExecutionID,
	}

	var (
		logMu    sync.Mutex
		toolLogs []ToolCallLog
	)

	qctx := rt.Context()

	// toolCallCount tracks the number of tool calls made so far. The counter
	// is shared across all registered tool functions via closure.
	var toolCallCount atomic.Int64

	// Build dispatch map keyed by "alias/toolName"
	dispatchMap := make(map[string]struct {
		call  func(jsonx.RawMessage) (jsonx.RawMessage, error)
		alias string
		tool  string
	})
	for alias, tools := range params.ServerTools {
		for _, tool := range tools {
			key := alias + "/" + tool.Name
			capturedAlias, capturedTool := alias, tool.Name
			dispatchMap[key] = struct {
				call  func(jsonx.RawMessage) (jsonx.RawMessage, error)
				alias string
				tool  string
			}{
				call: func(args jsonx.RawMessage) (jsonx.RawMessage, error) {
					if params.CallTool != nil {
						return params.CallTool(ctx, capturedAlias, capturedTool, args)
					}
					return nil, errors.New("no tool caller configured")
				},
				alias: capturedAlias,
				tool:  capturedTool,
			}
		}
	}

	// Register a single async dispatch function. The JS Proxy preamble calls
	// __callTool(alias, toolName, argsJSON) for every tool invocation.
	qctx.SetAsyncFunc("__callTool", func(this *qjs.This) {
		if params.MaxToolCalls > 0 && toolCallCount.Add(1) > int64(params.MaxToolCalls) {
			this.Promise().Reject(qctx.ThrowError(fmt.Errorf("tool call limit exceeded (max %d)", params.MaxToolCalls)))
			return
		}

		args := this.Args()
		if len(args) < 3 {
			for _, a := range args {
				a.Free()
			}
			this.Promise().Reject(qctx.ThrowError(fmt.Errorf("__callTool requires 3 arguments")))
			return
		}
		alias := args[0].String()
		toolName := args[1].String()
		rawArgs := jsonx.RawMessage(args[2].String())
		for _, a := range args {
			a.Free()
		}
		if len(rawArgs) == 0 {
			rawArgs = jsonx.RawMessage("{}")
		}

		key := alias + "/" + toolName
		entry, ok := dispatchMap[key]
		if !ok {
			logMu.Lock()
			toolLogs = append(toolLogs, ToolCallLog{Server: alias, Tool: toolName, Status: "error"})
			logMu.Unlock()
			this.Promise().Reject(qctx.ThrowError(fmt.Errorf("unknown tool: %s/%s", alias, toolName)))
			return
		}

		callStart := time.Now()
		callResult, callErr := entry.call(rawArgs)
		durationMS := time.Since(callStart).Milliseconds()

		status := "success"
		if callErr != nil {
			status = "error"
		}

		logMu.Lock()
		toolLogs = append(toolLogs, ToolCallLog{
			Server: entry.alias, Tool: entry.tool, DurationMS: durationMS, Status: status,
		})
		logMu.Unlock()

		if callErr != nil {
			this.Promise().Reject(qctx.ThrowError(callErr))
			return
		}
		unwrapped := unwrapToolResult(callResult)
		const maxCaptureSize = 1 << 20 // 1 MB — skip inference for huge responses to bound memory.
		if params.OnToolResult != nil && len(unwrapped) <= maxCaptureSize {
			captured := make(jsonx.RawMessage, len(unwrapped))
			copy(captured, unwrapped)
			go params.OnToolResult(entry.alias, entry.tool, captured)
		}
		this.Promise().Resolve(qctx.ParseJSON(string(unwrapped)))
	})

	preamble := buildProxyPreamble(params.ServerTools)
	// sandboxPreamble runs first to delete dangerous globals (std, os, console,
	// timers) before the tools preamble or user code can reference them.
	fullCode := sandboxPreamble + preamble + "\n" + params.Code

	// Recover from any panic inside Eval (e.g. WASM OOM) and mark the
	// runtime as unhealthy so the pool replaces it.
	defer func() {
		if r := recover(); r != nil {
			result.DurationMS = time.Since(start).Milliseconds()
			result.ToolCalls = snapshotToolLogs(&logMu, toolLogs)
			result.Error = fmt.Sprintf("runtime panic: %v", r)
			res = result
			retErr = nil
		}
	}()

	evalResult, evalErr := rt.Eval("code_mode.js", qjs.Code(fullCode), qjs.FlagAsync())

	result.DurationMS = time.Since(start).Milliseconds()
	result.ToolCalls = snapshotToolLogs(&logMu, toolLogs)
	result.Logs = extractConsoleLogs(rt)

	if evalErr != nil {
		result.Error = evalErr.Error()
		return result, nil
	}

	if evalResult != nil {
		// Always free the QJS value after extracting its content to avoid
		// leaking WASM memory. Values returned by Eval must be freed by
		// the caller per the fastschema/qjs memory management contract.
		encoded, encErr := valueToJSON(evalResult)
		evalResult.Free()
		if encErr != nil {
			result.Error = fmt.Sprintf("encode result: %s", encErr.Error())
		} else {
			result.Result = encoded
		}
	}

	return result, nil
}

// buildProxyPreamble generates a JavaScript preamble that uses ES6 Proxy
// objects to dispatch tool calls dynamically. The Proxy intercepts property
// access on the `tools` object: tools.alias.toolName(args) calls
// __callTool(alias, toolName, JSON.stringify(args || {})).
func buildProxyPreamble(serverTools map[string][]Tool) string {
	if len(serverTools) == 0 {
		return "const tools = {};\n"
	}

	var aliases []string
	for alias := range serverTools {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)

	var sb strings.Builder
	sb.WriteString("const __servers = new Set([")
	for i, alias := range aliases {
		if i > 0 {
			sb.WriteString(",")
		}
		b, _ := jsonx.Marshal(alias)
		sb.Write(b)
	}
	sb.WriteString("]);\n")
	sb.WriteString("const tools = new Proxy({}, {\n")
	sb.WriteString("  get(_, alias) {\n")
	sb.WriteString("    if (!__servers.has(alias)) return undefined;\n")
	sb.WriteString("    return new Proxy({}, {\n")
	sb.WriteString("      get(_, toolName) {\n")
	sb.WriteString("        return (args) => __callTool(alias, toolName, JSON.stringify(args || {}));\n")
	sb.WriteString("      }\n")
	sb.WriteString("    });\n")
	sb.WriteString("  }\n")
	sb.WriteString("});\n")
	return sb.String()
}

// valueToJSON converts a QJS *Value to a JSON-encoded byte slice. When the
// value is a JS string that is itself valid JSON (as produced by
// JSON.stringify inside the script), it is returned directly. Otherwise
// JSONStringify is called on the value to produce its JSON representation.
func valueToJSON(v *qjs.Value) (jsonx.RawMessage, error) {
	if v.IsString() {
		s := v.String()
		if jsonx.Valid([]byte(s)) {
			return jsonx.RawMessage(s), nil
		}
		// The string is not valid JSON on its own — encode it as a JSON string.
		b, err := jsonx.Marshal(s)
		if err != nil {
			return nil, fmt.Errorf("marshal string result: %w", err)
		}
		return jsonx.RawMessage(b), nil
	}

	s, err := v.JSONStringify()
	if err != nil {
		return nil, fmt.Errorf("JSONStringify result: %w", err)
	}
	if !jsonx.Valid([]byte(s)) {
		return nil, fmt.Errorf("JSONStringify returned invalid JSON: %s", s)
	}
	return jsonx.RawMessage(s), nil
}

// snapshotToolLogs returns a copy of the accumulated tool call logs under the
// provided mutex. It always returns a non-nil slice so that JSON serialisation
// produces an array rather than null.
func snapshotToolLogs(mu *sync.Mutex, logs []ToolCallLog) []ToolCallLog {
	mu.Lock()
	defer mu.Unlock()
	out := make([]ToolCallLog, len(logs))
	copy(out, logs)
	return out
}

// extractConsoleLogs reads the __logs array from the QJS global scope and
// returns it as a Go slice. The sandbox preamble installs a console replacement
// that pushes {level, msg} objects into __logs. Returns a non-nil empty slice
// if no logs were captured or if extraction fails.
func extractConsoleLogs(rt *qjs.Runtime) []ConsoleLog {
	logsVal, err := rt.Eval("__console_logs.js", qjs.Code("JSON.stringify(globalThis.__logs || [])"), qjs.FlagAsync())
	if err != nil {
		return []ConsoleLog{}
	}
	defer logsVal.Free()

	var logs []ConsoleLog
	if logsVal.IsString() {
		if jsonErr := jsonx.Unmarshal([]byte(logsVal.String()), &logs); jsonErr != nil {
			return []ConsoleLog{}
		}
	}
	if logs == nil {
		logs = []ConsoleLog{}
	}
	return logs
}
