{{- if and .Values.istio.enabled (not .Values.istio.gateway.name) }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ include "zanellm.fullname" . }}
  labels:
    {{- include "zanellm.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    {{- toYaml .Values.istio.gateway.servers | nindent 4 }}
{{- end }}
