{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "zanellm.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zanellm.fullname" . }}
  labels:
    {{- include "zanellm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.adminKey }}
  ZANELLM_ADMIN_KEY: {{ .Values.secrets.adminKey | b64enc | quote }}
  {{- else if and $existing $existing.data (index $existing.data "ZANELLM_ADMIN_KEY") }}
  ZANELLM_ADMIN_KEY: {{ index $existing.data "ZANELLM_ADMIN_KEY" }}
  {{- else }}
  ZANELLM_ADMIN_KEY: {{ randAlphaNum 48 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.encryptionKey }}
  ZANELLM_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  {{- else if and $existing $existing.data (index $existing.data "ZANELLM_ENCRYPTION_KEY") }}
  ZANELLM_ENCRYPTION_KEY: {{ index $existing.data "ZANELLM_ENCRYPTION_KEY" }}
  {{- else }}
  ZANELLM_ENCRYPTION_KEY: {{ randBytes 32 | b64enc | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.license }}
  ZANELLM_LICENSE: {{ .Values.secrets.license | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.ssoClientSecret }}
  ZANELLM_SSO_CLIENT_SECRET: {{ .Values.secrets.ssoClientSecret | b64enc | quote }}
  {{- end }}
  {{- range $key, $val := .Values.secrets.extraEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
