package db

import (
	"context"
	"testing"
)

// mustSetOrgMCPAccess sets the org MCP allowlist and fails the test on error.
func mustSetOrgMCPAccess(t *testing.T, d *DB, orgID string, serverIDs []string) {
	t.Helper()
	if err := d.SetOrgMCPAccess(context.Background(), orgID, serverIDs); err != nil {
		t.Fatalf("mustSetOrgMCPAccess(org=%q): %v", orgID, err)
	}
}

// mustSetTeamMCPAccess sets the team MCP allowlist and fails the test on error.
func mustSetTeamMCPAccess(t *testing.T, d *DB, teamID string, serverIDs []string) {
	t.Helper()
	if err := d.SetTeamMCPAccess(context.Background(), teamID, serverIDs); err != nil {
		t.Fatalf("mustSetTeamMCPAccess(team=%q): %v", teamID, err)
	}
}

// mustSetKeyMCPAccess sets the key MCP allowlist and fails the test on error.
func mustSetKeyMCPAccess(t *testing.T, d *DB, keyID string, serverIDs []string) {
	t.Helper()
	if err := d.SetKeyMCPAccess(context.Background(), keyID, serverIDs); err != nil {
		t.Fatalf("mustSetKeyMCPAccess(key=%q): %v", keyID, err)
	}
}

// setupMCPAccessFixture creates two MCP servers (global scope), an org, a team,
// and an API key. It returns all IDs needed by CheckMCPAccess tests.
//
// The two servers are named "target-<suffix>" and "other-<suffix>" and their IDs
// are generated by the DB. The caller receives the real IDs via serverA and serverB.
func setupMCPAccessFixture(t *testing.T, d *DB, suffix string) (orgID, teamID, keyID, serverA, serverB string) {
	t.Helper()
	svrA := mustCreateMCPServer(t, d, defaultMCPParams("target-"+suffix))
	svrB := mustCreateMCPServer(t, d, defaultMCPParams("other-"+suffix))
	org := mustCreateOrg(t, d, CreateOrgParams{Name: "Org " + suffix, Slug: "org-mcp-" + suffix})
	team := mustCreateTeam(t, d, CreateTeamParams{OrgID: org.ID, Name: "Team " + suffix, Slug: "team-mcp-" + suffix})
	user := mustCreateUser(t, d, CreateUserParams{Email: suffix + "@example.com", DisplayName: "User " + suffix})
	key := mustCreateAPIKey(t, d, testKeyParams(org.ID, user.ID, team.ID, user.ID))
	return org.ID, team.ID, key.ID, svrA.ID, svrB.ID
}

// ---- CheckMCPAccess -----------------------------------------------------------

// TestCheckMCPAccess_OrgNoEntries_Denied verifies the closed-by-default org policy:
// an org with no org_mcp_access entries must deny access to any server.
func TestCheckMCPAccess_OrgNoEntries_Denied(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, _ := setupMCPAccessFixture(t, d, "no-entries")

	got, err := d.CheckMCPAccess(context.Background(), orgID, teamID, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if got {
		t.Error("CheckMCPAccess() = true, want false (org is closed-by-default with no entries)")
	}
}

// TestCheckMCPAccess_OrgAllowed verifies that an org allowlist containing the
// server ID grants access when team and key have no restrictions.
func TestCheckMCPAccess_OrgAllowed(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, _ := setupMCPAccessFixture(t, d, "org-allowed")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverA})

	got, err := d.CheckMCPAccess(context.Background(), orgID, teamID, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if !got {
		t.Error("CheckMCPAccess() = false, want true (org allowlist contains server)")
	}
}

// TestCheckMCPAccess_OrgDenied verifies that an org allowlist that does NOT
// contain the server ID denies access.
func TestCheckMCPAccess_OrgDenied(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, serverB := setupMCPAccessFixture(t, d, "org-denied")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverB}) // only serverB is in the allowlist

	got, err := d.CheckMCPAccess(context.Background(), orgID, teamID, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if got {
		t.Error("CheckMCPAccess() = true, want false (server not in org allowlist)")
	}
}

// TestCheckMCPAccess_TeamNoEntries_Inherits verifies the open-by-default team
// policy: a team with no team_mcp_access rows inherits org access.
func TestCheckMCPAccess_TeamNoEntries_Inherits(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, _ := setupMCPAccessFixture(t, d, "team-inherit")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverA})
	// No team entries — team is open-by-default and inherits org access.

	got, err := d.CheckMCPAccess(context.Background(), orgID, teamID, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if !got {
		t.Error("CheckMCPAccess() = false, want true (team inherits from org)")
	}
}

// TestCheckMCPAccess_TeamRestricts verifies that a non-empty team allowlist
// that excludes the server ID overrides org-level access.
func TestCheckMCPAccess_TeamRestricts(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, serverB := setupMCPAccessFixture(t, d, "team-restricts")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverA})
	mustSetTeamMCPAccess(t, d, teamID, []string{serverB}) // team restricts to serverB only

	got, err := d.CheckMCPAccess(context.Background(), orgID, teamID, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if got {
		t.Error("CheckMCPAccess() = true, want false (team allowlist excludes server)")
	}
}

// TestCheckMCPAccess_KeyNoEntries_Inherits verifies the open-by-default key
// policy: a key with no key_mcp_access rows inherits team+org access.
func TestCheckMCPAccess_KeyNoEntries_Inherits(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, _ := setupMCPAccessFixture(t, d, "key-inherit")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverA})
	mustSetTeamMCPAccess(t, d, teamID, []string{serverA})
	// No key entries — key is open-by-default.

	got, err := d.CheckMCPAccess(context.Background(), orgID, teamID, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if !got {
		t.Error("CheckMCPAccess() = false, want true (key inherits from org+team)")
	}
}

// TestCheckMCPAccess_KeyRestricts verifies that a non-empty key allowlist that
// excludes the server ID overrides org+team-level access.
func TestCheckMCPAccess_KeyRestricts(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, serverB := setupMCPAccessFixture(t, d, "key-restricts")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverA})
	mustSetTeamMCPAccess(t, d, teamID, []string{serverA})
	mustSetKeyMCPAccess(t, d, keyID, []string{serverB}) // key restricts to serverB only

	got, err := d.CheckMCPAccess(context.Background(), orgID, teamID, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if got {
		t.Error("CheckMCPAccess() = true, want false (key allowlist excludes server)")
	}
}

// TestCheckMCPAccess_AllLevelsAllow verifies that access is granted when all
// three levels (org, team, key) explicitly include the server ID.
func TestCheckMCPAccess_AllLevelsAllow(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, serverB := setupMCPAccessFixture(t, d, "all-allow")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverA, serverB})
	mustSetTeamMCPAccess(t, d, teamID, []string{serverA})
	mustSetKeyMCPAccess(t, d, keyID, []string{serverA})

	got, err := d.CheckMCPAccess(context.Background(), orgID, teamID, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if !got {
		t.Error("CheckMCPAccess() = false, want true (all levels explicitly allow server)")
	}
}

// TestCheckMCPAccess_NoTeamID verifies that passing an empty teamID skips the
// team-level check and defers to org+key.
func TestCheckMCPAccess_NoTeamID(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, _, keyID, serverA, _ := setupMCPAccessFixture(t, d, "no-team-id")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverA})

	got, err := d.CheckMCPAccess(context.Background(), orgID, "" /* no team */, keyID, serverA)
	if err != nil {
		t.Fatalf("CheckMCPAccess() error = %v", err)
	}
	if !got {
		t.Error("CheckMCPAccess() = false, want true (no team check, org allows)")
	}
}

// ---- LoadAllMCPAccess ---------------------------------------------------------

// TestLoadAllMCPAccess_Empty verifies that LoadAllMCPAccess returns empty maps
// when no access entries exist.
func TestLoadAllMCPAccess_Empty(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)

	org, team, key, err := d.LoadAllMCPAccess(context.Background())
	if err != nil {
		t.Fatalf("LoadAllMCPAccess() error = %v", err)
	}
	if len(org) != 0 {
		t.Errorf("org map len = %d, want 0", len(org))
	}
	if len(team) != 0 {
		t.Errorf("team map len = %d, want 0", len(team))
	}
	if len(key) != 0 {
		t.Errorf("key map len = %d, want 0", len(key))
	}
}

// TestLoadAllMCPAccess_PopulatesAllMaps verifies that LoadAllMCPAccess returns
// correct entries for org, team, and key scopes after data is inserted.
func TestLoadAllMCPAccess_PopulatesAllMaps(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	orgID, teamID, keyID, serverA, serverB := setupMCPAccessFixture(t, d, "load-all")
	mustSetOrgMCPAccess(t, d, orgID, []string{serverA, serverB})
	mustSetTeamMCPAccess(t, d, teamID, []string{serverA})
	mustSetKeyMCPAccess(t, d, keyID, []string{serverB})

	org, team, key, err := d.LoadAllMCPAccess(context.Background())
	if err != nil {
		t.Fatalf("LoadAllMCPAccess() error = %v", err)
	}

	orgServers := org[orgID]
	if len(orgServers) != 2 {
		t.Errorf("org[%q] len = %d, want 2", orgID, len(orgServers))
	}

	teamServers := team[teamID]
	if len(teamServers) != 1 || teamServers[0] != serverA {
		t.Errorf("team[%q] = %v, want [%s]", teamID, teamServers, serverA)
	}

	keyServers := key[keyID]
	if len(keyServers) != 1 || keyServers[0] != serverB {
		t.Errorf("key[%q] = %v, want [%s]", keyID, keyServers, serverB)
	}
}

// ---- SetOrgMCPAccess / GetOrgMCPAccess round-trip ----------------------------

// TestSetOrgMCPAccess_ReplacesExisting verifies that calling SetOrgMCPAccess a
// second time atomically replaces the previous allowlist.
func TestSetOrgMCPAccess_ReplacesExisting(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	svrA := mustCreateMCPServer(t, d, defaultMCPParams("replace-a"))
	svrB := mustCreateMCPServer(t, d, defaultMCPParams("replace-b"))
	svrC := mustCreateMCPServer(t, d, defaultMCPParams("replace-c"))
	org := mustCreateOrg(t, d, CreateOrgParams{Name: "Replace Org", Slug: "replace-org-mcp"})

	mustSetOrgMCPAccess(t, d, org.ID, []string{svrA.ID, svrB.ID})
	mustSetOrgMCPAccess(t, d, org.ID, []string{svrC.ID}) // replace

	got, err := d.GetOrgMCPAccess(context.Background(), org.ID)
	if err != nil {
		t.Fatalf("GetOrgMCPAccess() error = %v", err)
	}
	if len(got) != 1 || got[0] != svrC.ID {
		t.Errorf("GetOrgMCPAccess() = %v, want [%s]", got, svrC.ID)
	}
}

// TestSetOrgMCPAccess_ClearList verifies that passing an empty slice removes all
// entries for the org (closed-by-default, no access).
func TestSetOrgMCPAccess_ClearList(t *testing.T) {
	t.Parallel()

	d := openMigratedDB(t)
	svrA := mustCreateMCPServer(t, d, defaultMCPParams("clear-a"))
	org := mustCreateOrg(t, d, CreateOrgParams{Name: "Clear Org", Slug: "clear-org-mcp"})

	mustSetOrgMCPAccess(t, d, org.ID, []string{svrA.ID})
	mustSetOrgMCPAccess(t, d, org.ID, nil) // clear

	got, err := d.GetOrgMCPAccess(context.Background(), org.ID)
	if err != nil {
		t.Fatalf("GetOrgMCPAccess() error = %v", err)
	}
	if len(got) != 0 {
		t.Errorf("GetOrgMCPAccess() = %v, want empty after clear", got)
	}
}
